apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Name }}
  namespace: argocd
spec:
  project: default
  source:
    chart: {{ .Helm.Chart }}
    repoURL: {{ .Helm.RepoURL }}
    targetRevision: {{ .Helm.TargetRevision }}
    helm:
      releaseName: {{ .Helm.ReleaseName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true